// default package
// Generated Jan 20, 2021, 10:30:57 AM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clients generated by hbm2java
 */

@Entity
@Table(name = "clients", catalog = "clients_management")
public class Clients implements java.io.Serializable {

	private String dni;
	private String nom;
	private boolean premium;
	private Set<Comandes> comandes = new HashSet<Comandes>(0);

	public Clients() {
	}

	public Clients(String dni) {
		this.dni = dni;
	}

	public Clients(String dni, String nom, boolean premium) {
		this.dni = dni;
		this.nom = nom;
		this.premium = premium;
	}

	@Id
	//@GeneratedValue
	@Column(name = "dni", unique = true, nullable = false, length = 8)	
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nom", length = 30)	
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	
	/** ALLOW THE CONVERTION DATATYPES BOOLEAN-ENUM */
	//define an enum type because the attribute premium is ENUM('S','N') in MySQL DB
	//there is the need to parse the datatypes Boolean-Enum
	public enum SNEnumType{ S,N }

	//link: https://thorben-janssen.com/hibernate-enum-mappings/
	//link: https://www.youtube.com/watch?v=xIvPDZnaFpM
	@Column(name = "premium")
	//@Enumerated(EnumType.STRING)
	@Convert(converter = BooleanEnumConverter.class)	
	public boolean getPremium() {
		return this.premium;
	}

	public void setPremium(boolean premium) {
		this.premium = premium;
	}

	
	//1.0
	//@OneToMany(mappedBy="clients")
	
	//2.0
	@OneToMany
	@JoinColumn(name="clients")
	public Set<Comandes> getComandeses() {
		return this.comandes;
	}

	public void setComandeses(Set<Comandes> comandeses) {
		this.comandes = comandeses;
	}

}
