// default package
// Generated Jan 20, 2021, 10:30:57 AM by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TemporalType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import javax.persistence.Temporal;

/**
 * Comandes generated by hbm2java
 */

@Entity
@Table(name="comandes", catalog="clients_management")
public class Comandes implements java.io.Serializable {

	private String numComanda;
	private Clients clients;
	private Float preuTotal;
	private Date data;
	private Set<ResumFacturacio> resumFacturacios = new HashSet<ResumFacturacio>(0);

	public Comandes() {
	}

	public Comandes(String numComanda) {
		this.numComanda = numComanda;
	}

	public Comandes(String numComanda, Clients clients, Float preuTotal, 
			Date data) {
			/*,Set resumFacturacios) { */
		this.numComanda = numComanda;
		this.clients = clients;
		this.preuTotal = preuTotal;
		this.data = data;
		//this.resumFacturacios = resumFacturacios;
	}

	@Id	
	@Column(name = "num_comanda", unique = true, nullable = false, length = 8)		
	public String getNumComanda() {
		return this.numComanda;
	}

	public void setNumComanda(String numComanda) {
		this.numComanda = numComanda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="dni_client")
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@Column(name="preu_total")
	public Float getPreuTotal() {
		return this.preuTotal;
	}

	public void setPreuTotal(Float preuTotal) {
		this.preuTotal = preuTotal;
	}

	@Temporal(TemporalType.DATE)	
	@Column(name="data")
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	/*
	public Set getResumFacturacios() {
		return this.resumFacturacios;
	}

	public void setResumFacturacios(Set resumFacturacios) {
		this.resumFacturacios = resumFacturacios;
	}
	 */
	
	@Override
	public String toString() {
		return "Dades Comanda\nnum_comanda=" + numComanda + "\nclient=" + clients.getDni() + "\npreuTotal=" + preuTotal + "\ndata="
				+ data;
	}

}
