// default package
// Generated Jan 20, 2021, 10:30:57 AM by Hibernate Tools 5.4.21.Final

/**
 * ResumFacturacio generated by hbm2java
 */
public class ResumFacturacio implements java.io.Serializable {

	private ResumFacturacioId id;
	private Comandes comandes;
	private Float totalMes;

	public ResumFacturacio() {
	}

	public ResumFacturacio(ResumFacturacioId id, Comandes comandes) {
		this.id = id;
		this.comandes = comandes;
	}

	public ResumFacturacio(ResumFacturacioId id, Comandes comandes, Float totalMes) {
		this.id = id;
		this.comandes = comandes;
		this.totalMes = totalMes;
	}

	public ResumFacturacioId getId() {
		return this.id;
	}

	public void setId(ResumFacturacioId id) {
		this.id = id;
	}

	public Comandes getComandes() {
		return this.comandes;
	}

	public void setComandes(Comandes comandes) {
		this.comandes = comandes;
	}

	public Float getTotalMes() {
		return this.totalMes;
	}

	public void setTotalMes(Float totalMes) {
		this.totalMes = totalMes;
	}

}
