// default package
// Generated Jan 20, 2021, 10:30:57 AM by Hibernate Tools 5.4.21.Final

/**
 * ResumFacturacioId generated by hbm2java
 */
public class ResumFacturacioId implements java.io.Serializable {

	private int mes;
	private int any;
	private String dniClientResum;

	public ResumFacturacioId() {
	}

	public ResumFacturacioId(int mes, int any, String dniClientResum) {
		this.mes = mes;
		this.any = any;
		this.dniClientResum = dniClientResum;
	}

	public int getMes() {
		return this.mes;
	}

	public void setMes(int mes) {
		this.mes = mes;
	}

	public int getAny() {
		return this.any;
	}

	public void setAny(int any) {
		this.any = any;
	}

	public String getDniClientResum() {
		return this.dniClientResum;
	}

	public void setDniClientResum(String dniClientResum) {
		this.dniClientResum = dniClientResum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResumFacturacioId))
			return false;
		ResumFacturacioId castOther = (ResumFacturacioId) other;

		return (this.getMes() == castOther.getMes()) && (this.getAny() == castOther.getAny())
				&& ((this.getDniClientResum() == castOther.getDniClientResum())
						|| (this.getDniClientResum() != null && castOther.getDniClientResum() != null
								&& this.getDniClientResum().equals(castOther.getDniClientResum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMes();
		result = 37 * result + this.getAny();
		result = 37 * result + (getDniClientResum() == null ? 0 : this.getDniClientResum().hashCode());
		return result;
	}

}
